name: Main

on:
  pull_request:
  push:
    branches:
      - master
      - trunk
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v6
      - name: Execute Gradle build
        run: ./gradlew build

  # Status check that is required in branch protection rules.
  final-status:
    needs:
      - build
    runs-on: ubuntu-slim
    if: always()
    steps:
      - name: Check
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            echo "One or more required jobs failed"
            exit 1
          fi
          echo "All required jobs completed successfully."
