name: Run Gradle on PRs
on: [pull_request, push]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [8, 11, 17, 19]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'zulu'
    - uses: gradle/wrapper-validation-action@v1.0.3
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build --scan
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
